### PR TITLE
added a failing test with 2 triminos on a 3x3 board

### PR DESCRIPTION
**Pull request by parmentelat**
I am trying to troubleshoot a problem I am facing with this library

running the same code on 2 arrays that are apparently similar (i.e. same shape & dtype & values)
get_exact_cover() exhibits 2 different behaviors:
with one it finds the right answer
and with the other it does not find any solution

the problem is with the array that is built programmatically - as opposed to being loaded from a file

this is totally weird as far as I am concerned, this goes against all common sense

in my application I worked around this problem by simply saving/reloading the numpy array before I feed it to get_exact_cover()

### CODE REVIEW

**Comment by jwg4** [comment]
Thanks so much for reporting this! I will take a look at try to figure out what's going on.

**Comment by jwg4** [comment]
hi @parmentelat is it correct that when you run these 3 new tests, the one that fails is `test_input1()` ? 

because on my dev machine and for the github actions runs that I checked, this test passes and `test_input2()` fails.

eg see https://github.com/jwg4/exact_cover/actions/runs/6571872161

**Comment by parmentelat** [comment]
hi @jwg4 

running the tests on my laptop again this morning, I also see that the failing test is `test_input2`

which blows my mind because at the very beginning of all this, I was running into problems with arrays that were built by program (like test_input1), and my workaround is to save/load them (like test_input2)

I also checked again with my commit 6623a65 and that was already like that
I am at a total loss to give any sensible explanation, but it probably means that I jumped to conclusions at some point, and assumed the failing test was test1 while in fact it was test2

in any case there still is something very fishy here, and I hope your future findings will help us understand what's going on

let me know if I can help any other way

**Comment by jwg4** [comment]
Hi, I think I understood this one.
Numpy saves 2d arrays in two internal representations, Fortran order (aka column-major order) and C order (aka row-major order).

exact-cover uses the internal representation directly, but doesn't check which order the array is laid out in. *It should*. reading the array row-by-row when it's laid out column-by-column gives nonsense.

it appears that in the vast majority of cases, arrays are laid-out in C order anyway so everything is fine.

my guess is that for some reason, something you were doing in your code meant that you got Fortran order. Then when you wrote a table to disk using the numpy binary format, that array stayed in Fortran order. So now it's a good example of an array which breaks. (And for some reason, when you wrote and read from file before, it transformed the layout order. I don't know why this happened. I guess that numpy has different approaches to choosing order or accepting an already present order based on the source of data?)

fix and new tests for this coming soon - unless I find that I can't confirm this theory...

**Comment by parmentelat** [comment]
hiya - good to hear that you turned up with something :)
it does sound quite possible at first sight, at least it could explain this otherwise mysterious behaviour
Ill stay tuned in any case - thanks for looking into this 👍

**Review by jwg4 — APPROVED** [review]
I have done some work to mitigate these issues on a separate branch but I think it's worth to include these tests.

**Comment by jwg4** [comment]
Hi, the fix to this is now merged to master and also on pypi as a prerelease version https://pypi.org/project/exact_cover/1.3.0a0/

It will be a full version soon but in the meantime if you are able to confirm that this works for you now that would be great.

**Comment by parmentelat** [comment]
hey @jwg4 
I can confirm that 1.3.0 works for me wrt this issue
Thanks !

**Pull request merged**
