### PR TITLE
get the tests to pass

### PR DESCRIPTION
**Pull request by parmentelat**
on my system at least, I am seeing the tests failing

## my versions

```
macos 12.6.8 / intel
python 3.11.5
numpy 1.25.2
```

## the symptoms

<details><summary>poetry run test</summary>

```
======================================================== test session starts =========================================================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/xxx/git/exact_cover
configfile: pyproject.toml
plugins: hypothesis-6.84.3
collected 39 items

README.md F                                                                                                                    [  2%]
examples.md F                                                                                                                  [  5%]
exact_cover/helpers.py .                                                                                                       [  7%]
my-playground/test_exact_cover.py .                                                                                            [ 10%]
tests/test_exact_cover.py .......                                                                                              [ 28%]
tests/test_exact_cover_problems.py ...                                                                                         [ 35%]
tests/test_helpers.py .............                                                                                            [ 69%]
tests/test_io.py .                                                                                                             [ 71%]
tests/test_sudoku_based.py ...........                                                                                         [100%]

============================================================== FAILURES ==============================================================
________________________________________________________ [doctest] README.md _________________________________________________________
059     B = 1,1,1,0,0    # The 0th, 1st, and 2nd entries are 1, and the rest are 0,
060     C = 0,1,1,0,0    # etc.
061     D = 0,0,0,0,1
062
063 Now we can call `exact_cover`:
064
065     >>> import numpy as np
066     >>> import exact_cover as ec
067     >>> S = np.array([[1,0,0,1,0],[1,1,1,0,0],[0,1,1,0,0],[0,0,0,0,1]], dtype=bool)
068     >>> ec.get_exact_cover(S)
Expected:
    array([0, 2, 3])
Got:
    array([0, 2, 3], dtype=int32)

/Users/xxx/git/exact_cover/README.md:68: DocTestFailure
_______________________________________________________ [doctest] examples.md ________________________________________________________
004
005     >>> import exact_cover as ec
006
007 Input and output to the package are using the numpy array type:
008
009     >>> import numpy as np
010
011 This example is explained in README.md
012     >>> S = np.array([[1,0,0,1,0],[1,1,1,0,0],[0,1,1,0,0],[0,0,0,0,1]], dtype=np.int32)
013     >>> ec.get_exact_cover(S)
Expected:
    array([0, 2, 3])
Got:
    array([0, 2, 3], dtype=int32)

/Users/xxx/git/exact_cover/examples.md:13: DocTestFailure
====================================================== short test summary info =======================================================
FAILED README.md::README.md
FAILED examples.md::examples.md
=================================================== 2 failed, 37 passed in 10.06s ====================================================
```
</details>

<details>
<summary>poetry run doctest</summary>
**********************************************************************
File "/Users/xxx/git/exact_cover/tools/../README.md", line 68, in README.md
Failed example:
    ec.get_exact_cover(S)
Expected:
    array([0, 2, 3])
Got:
    array([0, 2, 3], dtype=int32)
**********************************************************************
1 items had failures:
   1 of   4 in README.md
***Test Failed*** 1 failures.
**********************************************************************
File "/Users/xxx/git/exact_cover/tools/../examples.md", line 13, in examples.md
Failed example:
    ec.get_exact_cover(S)
Expected:
    array([0, 2, 3])
Got:
    array([0, 2, 3], dtype=int32)
**********************************************************************
File "/Users/xxx/git/exact_cover/tools/../examples.md", line 19, in examples.md
Failed example:
    ec.get_exact_cover(T)
Expected:
    array([0, 2, 3])
Got:
    array([0, 2, 3], dtype=int32)
**********************************************************************
1 items had failures:
   2 of   7 in examples.md
***Test Failed*** 2 failures.
```
</details>

### CODE REVIEW

**Comment by jwg4** [comment]
Hi, thank you so much for this!

I don't think your change will be workable as on my system the types are not displayed.

I have changed the doctests to use, hopefully, a representation of arrays which is stable. Would you by any chance be able to checks pass for you on my new branch #66 ? 

I will also try to add your setup to the list of ones which are tested against.

**Comment by parmentelat** [comment]
Hi
I can confirm that the fix_array_display branch solves the problem, and the tests now pass fine on my laptop
thanks for taking care of this :)

**Comment by jwg4** [comment]
Great, now to look at the much more interesting/scary bug you also
reported...

**Comment by jwg4** [comment]
thanks so much for this, fixed on another branch as discussed

**Pull request closed without merging**
